language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: f0e905c2480fc525702e7aac15452ac3ccadeb70
 local_dir: dist
 on:
   branch: master